import type { Project, Experience } from '@/db/schema'

// Mock project data for design preview
export const mockProjects: Project[] = [
  {
    id: '1',
    userId: 'user-1',
    name: 'CodeCave Platform',
    description: 'A modern developer community platform built with Next.js 15, featuring real-time collaboration, project showcasing, and networking capabilities. Includes advanced features like AI-powered code analysis and integrated video calling.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'Drizzle ORM', 'Zustand'],
    githubUrl: 'https://github.com/username/codecave',
    liveUrl: 'https://codecave.dev',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop',
    stars: 247,
    forks: 32,
    isPrivate: false,
    language: 'TypeScript',
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-08-20T15:30:00Z'),
  },
  {
    id: '2',
    userId: 'user-1',
    name: 'AI Task Manager',
    description: 'An intelligent task management application that uses machine learning to prioritize tasks and suggest optimal scheduling. Features natural language processing for task creation and smart notifications.',
    technologies: ['React', 'Python', 'FastAPI', 'PostgreSQL', 'OpenAI API', 'Docker'],
    githubUrl: 'https://github.com/username/ai-task-manager',
    liveUrl: 'https://aitasks.app',
    imageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=400&fit=crop',
    stars: 89,
    forks: 12,
    isPrivate: false,
    language: 'Python',
    createdAt: new Date('2023-09-10T14:20:00Z'),
    updatedAt: new Date('2024-03-15T09:45:00Z'),
  },
  {
    id: '3',
    userId: 'user-1',
    name: 'Mobile Weather App',
    description: 'A beautiful cross-platform weather application with animated UI, location-based forecasts, and weather alerts. Includes widgets and Apple Watch integration.',
    technologies: ['React Native', 'Expo', 'TypeScript', 'Reanimated', 'Weather API'],
    githubUrl: 'https://github.com/username/weather-app',
    liveUrl: null,
    imageUrl: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800&h=400&fit=crop',
    stars: 156,
    forks: 23,
    isPrivate: false,
    language: 'JavaScript',
    createdAt: new Date('2023-06-01T11:30:00Z'),
    updatedAt: new Date('2023-12-20T16:15:00Z'),
  },
  {
    id: '4',
    userId: 'user-1',
    name: 'E-commerce Analytics Dashboard',
    description: 'A comprehensive analytics dashboard for e-commerce businesses with real-time sales tracking, customer insights, and predictive analytics. Features advanced data visualization and automated reporting.',
    technologies: ['Vue.js', 'Nuxt.js', 'Chart.js', 'Node.js', 'MongoDB', 'Redis'],
    githubUrl: null,
    liveUrl: 'https://ecommerce-analytics.demo',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
    stars: 0,
    forks: 0,
    isPrivate: true,
    language: 'Vue',
    createdAt: new Date('2024-04-22T08:15:00Z'),
    updatedAt: new Date('2024-07-30T12:00:00Z'),
  },
]

// Mock experience data for design preview
export const mockExperiences: Experience[] = [
  {
    id: '1',
    userId: 'user-1',
    company: 'TechCorp Solutions',
    position: 'Senior Full Stack Engineer',
    description: 'Led a team of 5 developers in building scalable web applications for enterprise clients. Architected microservices infrastructure that improved system performance by 40% and reduced deployment time by 60%. Mentored junior developers and established best practices for code review and testing.',
    location: 'San Francisco, CA',
    companyUrl: 'https://techcorp.com',
    companyLogo: 'https://logo.clearbit.com/techcorp.com',
    employmentType: 'full-time',
    startDate: '2022-03-01',
    endDate: null,
    isCurrent: true,
    technologies: ['React', 'Node.js', 'TypeScript', 'AWS', 'Docker', 'Kubernetes', 'PostgreSQL'],
    achievements: [
      'Led migration from monolith to microservices architecture',
      'Reduced API response time by 40% through optimization',
      'Mentored 3 junior developers to mid-level positions',
      'Implemented automated testing pipeline with 95% coverage'
    ],
    isPrivate: false,
    isFeatured: true,
    sortOrder: '1',
    createdAt: new Date('2022-03-01T09:00:00Z'),
    updatedAt: new Date('2024-08-20T10:30:00Z'),
  },
  {
    id: '2',
    userId: 'user-1',
    company: 'StartupXYZ',
    position: 'Frontend Developer',
    description: 'Developed responsive web applications using modern React ecosystem. Collaborated closely with design team to implement pixel-perfect UI components and improved user experience. Built reusable component library used across multiple products.',
    location: 'Remote',
    companyUrl: 'https://startupxyz.io',
    companyLogo: 'https://logo.clearbit.com/startupxyz.io',
    employmentType: 'full-time',
    startDate: '2020-06-15',
    endDate: '2022-02-28',
    isCurrent: false,
    technologies: ['React', 'JavaScript', 'Sass', 'Webpack', 'Jest', 'Storybook'],
    achievements: [
      'Built component library used by 4 product teams',
      'Improved page load speed by 35% through optimization',
      'Implemented responsive design system',
      'Collaborated with design team on user research'
    ],
    isPrivate: false,
    isFeatured: false,
    sortOrder: '2',
    createdAt: new Date('2020-06-15T09:00:00Z'),
    updatedAt: new Date('2022-02-28T17:00:00Z'),
  },
  {
    id: '3',
    userId: 'user-1',
    company: 'Freelance',
    position: 'Full Stack Developer',
    description: 'Worked with various clients to build custom web applications and e-commerce solutions. Managed complete project lifecycle from requirements gathering to deployment and maintenance. Specialized in MEAN/MERN stack development.',
    location: 'Remote',
    companyUrl: null,
    companyLogo: null,
    employmentType: 'freelance',
    startDate: '2019-01-01',
    endDate: '2020-06-01',
    isCurrent: false,
    technologies: ['Angular', 'Node.js', 'MongoDB', 'Express.js', 'React', 'MySQL'],
    achievements: [
      'Delivered 12+ projects on time and within budget',
      'Built e-commerce platform handling $50K+ monthly transactions',
      'Maintained 100% client satisfaction rating',
      'Developed real-time chat application for 500+ users'
    ],
    isPrivate: false,
    isFeatured: false,
    sortOrder: '3',
    createdAt: new Date('2019-01-01T09:00:00Z'),
    updatedAt: new Date('2020-06-01T17:00:00Z'),
  },
  {
    id: '4',
    userId: 'user-1',
    company: 'MegaCorp Inc',
    position: 'Junior Software Developer',
    description: 'Started my professional journey as a junior developer working on internal tools and customer-facing applications. Gained experience in enterprise software development practices and agile methodologies.',
    location: 'New York, NY',
    companyUrl: 'https://megacorp.com',
    companyLogo: 'https://logo.clearbit.com/megacorp.com',
    employmentType: 'full-time',
    startDate: '2018-07-01',
    endDate: '2018-12-31',
    isCurrent: false,
    technologies: ['Java', 'Spring Boot', 'MySQL', 'JavaScript', 'jQuery', 'Bootstrap'],
    achievements: [
      'Contributed to 3 major product releases',
      'Fixed 50+ bugs and implemented 20+ features',
      'Completed internal training program with distinction',
      'Participated in code review process'
    ],
    isPrivate: false,
    isFeatured: false,
    sortOrder: '4',
    createdAt: new Date('2018-07-01T09:00:00Z'),
    updatedAt: new Date('2018-12-31T17:00:00Z'),
  },
]