import type { ConnectionUser, ConnectionInvitation, NetworkStats } from '@/types/connections'

export const mockConnectionsSuggestions: ConnectionUser[] = [
  {
    id: '1',
    username: 'sarahchen',
    displayName: 'Sarah Chen',
    bio: 'Senior Frontend Engineer at Google. React & TypeScript enthusiast.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=400&h=400&fit=crop',
    skills: ['React', 'TypeScript', 'Next.js'],
    experienceLevel: 'senior',
    availableForCollab: true,
    mutualConnections: 12,
    githubUsername: 'sarahc',
    location: 'San Francisco, CA',
    lastActive: new Date('2025-08-18T10:30:00Z'),
  },
  {
    id: '2',
    username: 'alexkumar',
    displayName: 'Alex Kumar',
    bio: 'Full-stack developer building the future of web development.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    skills: ['Node.js', 'Python', 'PostgreSQL'],
    experienceLevel: 'mid',
    availableForCollab: true,
    mutualConnections: 8,
    githubUsername: 'alexk',
    location: 'Austin, TX',
    lastActive: new Date('2025-08-18T08:15:00Z'),
  },
  {
    id: '3',
    username: 'emilyjohnson',
    displayName: 'Emily Johnson',
    bio: 'DevOps Engineer passionate about automation and cloud infrastructure.',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    experienceLevel: 'senior',
    availableForCollab: false,
    mutualConnections: 15,
    githubUsername: 'emilyj',
    location: 'Seattle, WA',
    lastActive: new Date('2025-08-18T12:45:00Z'),
  },
  {
    id: '4',
    username: 'mikereynolds',
    displayName: 'Mike Reynolds',
    bio: 'Mobile developer crafting beautiful iOS and Android experiences.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    skills: ['React Native', 'Swift', 'Kotlin'],
    experienceLevel: 'mid',
    availableForCollab: true,
    mutualConnections: 6,
    githubUsername: 'mikerey',
    location: 'New York, NY',
    lastActive: new Date('2025-08-18T09:20:00Z'),
  },
  {
    id: '5',
    username: 'lisawang',
    displayName: 'Lisa Wang',
    bio: 'Data scientist turning data into insights with Python and ML.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face',
    skills: ['Python', 'TensorFlow', 'SQL'],
    experienceLevel: 'senior',
    availableForCollab: true,
    mutualConnections: 9,
    githubUsername: 'lisawang',
    location: 'Toronto, ON',
    lastActive: new Date('2025-08-18T11:10:00Z'),
  },
  {
    id: '6',
    username: 'davidlee',
    displayName: 'David Lee',
    bio: 'Backend engineer scaling systems for millions of users.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    skills: ['Go', 'Microservices', 'Redis'],
    experienceLevel: 'lead',
    availableForCollab: false,
    mutualConnections: 18,
    githubUsername: 'davidlee',
    location: 'London, UK',
    lastActive: new Date('2025-08-18T07:30:00Z'),
  },
]

export const mockMyConnections: ConnectionUser[] = [
  {
    id: '11',
    username: 'tomwilson',
    displayName: 'Tom Wilson',
    bio: 'Frontend architect and React ecosystem contributor.',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face',
    skills: ['React', 'JavaScript', 'GraphQL'],
    experienceLevel: 'senior',
    availableForCollab: true,
    githubUsername: 'tomw',
    location: 'Los Angeles, CA',
    connectedAt: new Date('2025-07-15T14:20:00Z'),
    lastActive: new Date('2025-08-18T13:45:00Z'),
  },
  {
    id: '12',
    username: 'rachelgreen',
    displayName: 'Rachel Green',
    bio: 'UX Engineer bridging design and development.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face',
    skills: ['React', 'Figma', 'CSS'],
    experienceLevel: 'mid',
    availableForCollab: true,
    githubUsername: 'rachelg',
    location: 'Chicago, IL',
    connectedAt: new Date('2025-06-10T09:30:00Z'),
    lastActive: new Date('2025-08-18T16:20:00Z'),
  },
  {
    id: '13',
    username: 'jamespark',
    displayName: 'James Park',
    bio: 'Backend engineer specializing in distributed systems.',
    avatarUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=400&h=400&fit=crop&crop=face',
    skills: ['Java', 'Spring', 'Kafka'],
    experienceLevel: 'senior',
    availableForCollab: false,
    githubUsername: 'jpark',
    location: 'San Jose, CA',
    connectedAt: new Date('2025-05-22T11:15:00Z'),
    lastActive: new Date('2025-08-17T20:10:00Z'),
  },
]

export const mockInvitations: ConnectionInvitation[] = [
  {
    id: 'inv1',
    user: {
      id: '21',
      username: 'annasmith',
      displayName: 'Anna Smith',
      bio: 'Product Manager turning ideas into impactful products.',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face',
      skills: ['Product Management', 'Analytics', 'UX'],
      experienceLevel: 'senior',
      availableForCollab: true,
      mutualConnections: 3,
      githubUsername: 'annas',
      location: 'Boston, MA',
    },
    message: "Hi! I'd love to connect and discuss potential collaboration opportunities in the React ecosystem.",
    sentAt: new Date('2025-08-17T14:30:00Z'),
    type: 'received',
  },
  {
    id: 'inv2',
    user: {
      id: '22',
      username: 'carlosrodriguez',
      displayName: 'Carlos Rodriguez',
      bio: 'DevOps engineer automating the world, one pipeline at a time.',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face',
      skills: ['Docker', 'CI/CD', 'AWS'],
      experienceLevel: 'mid',
      availableForCollab: true,
      mutualConnections: 7,
      githubUsername: 'carlosr',
      location: 'Madrid, Spain',
    },
    sentAt: new Date('2025-08-16T10:20:00Z'),
    type: 'received',
  },
]

export const mockFollowing: ConnectionUser[] = [
  {
    id: '31',
    username: 'techguru',
    displayName: 'Tech Guru',
    bio: 'Sharing insights about the latest in web development.',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop&crop=face',
    skills: ['React', 'Vue', 'Angular'],
    experienceLevel: 'lead',
    availableForCollab: false,
    githubUsername: 'techguru',
    location: 'Remote',
    lastActive: new Date('2025-08-18T15:30:00Z'),
  },
  {
    id: '32',
    username: 'designdev',
    displayName: 'Design Dev',
    bio: 'Where design meets code. Building beautiful, functional interfaces.',
    avatarUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face',
    skills: ['CSS', 'Figma', 'React'],
    experienceLevel: 'senior',
    availableForCollab: true,
    githubUsername: 'designdev',
    location: 'Portland, OR',
    lastActive: new Date('2025-08-18T14:15:00Z'),
  },
]

export const mockFollowers: ConnectionUser[] = [
  {
    id: '41',
    username: 'junior_dev',
    displayName: 'Alex Developer',
    bio: 'Junior developer eager to learn and grow in the tech industry.',
    avatarUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop&crop=face',
    skills: ['JavaScript', 'HTML', 'CSS'],
    experienceLevel: 'junior',
    availableForCollab: true,
    githubUsername: 'alexdev',
    location: 'Phoenix, AZ',
    lastActive: new Date('2025-08-18T12:00:00Z'),
  },
  {
    id: '42',
    username: 'codestudent',
    displayName: 'Sam Student',
    bio: 'Computer Science student passionate about full-stack development.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696485-84bcaf42ba19?w=400&h=400&fit=crop&crop=face',
    skills: ['Python', 'Django', 'React'],
    experienceLevel: 'student',
    availableForCollab: true,
    githubUsername: 'samstudent',
    location: 'Austin, TX',
    lastActive: new Date('2025-08-18T16:45:00Z'),
  },
]

export const mockNetworkStats: NetworkStats = {
  totalConnections: 247,
  newThisWeek: 5,
  newThisMonth: 18,
  networkReach: 12500,
  profileViews: 89,
  growthRate: 12.5,
}

export const mockConnectionsData = {
  suggestions: mockConnectionsSuggestions,
  myConnections: mockMyConnections,
  invitations: mockInvitations,
  following: mockFollowing,
  followers: mockFollowers,
  stats: mockNetworkStats,
}